=== LedgerHQ/web3allowlist/dapps/dapp-allowlist.schema.json
{
  "$id": "https://ledger.com/allowlist.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of a ledger allowlist",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "schemaVersion": {
      "type": "integer",
      "description": "The schema of the allowlist"
    },
    "$schema": {
      "type": "string",
      "description": "The schema of the allowlist"
    },
    "name": {
      "type": "string",
      "description": "The name of the allowlist"
    },
    "domain": {
      "type": "string",
      "description": "The domain of the allowlist"
    },
    "subdomains": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string",
      "description": "A description of the allowlist"
    },
    "chains": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/chain"
      }
    }
  },
  "required": ["name", "domain", "chains"],
  "$defs": {
    "chain": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/contract"
      }
    },
    "contract": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string",
          "description": "The address of the contract"
        },
        "description": {
          "type": "string",
          "description": "A description of the contract"
        }
      },
      "required": ["address"]
    }
  }
}

=== LedgerHQ/web3allowlist/dapps/cryptomultisender.com/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Cryptomultisender",
  "domain": "cryptomultisender.com",
  "chains": {
    "polygon": [
      {
        "address": "0xb8615ad742c604e2920a82fdfcdd6cd93c56b4b7"
      }
    ],
    "ethereum": [
      {
        "address": "0xbbba5ba03d948d0a4cc010ca03d3b6e1b14f7098"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/bridge.degen.tips/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Degen",
  "domain": "bridge.degen.tips",
  "chains": {
    "base": [
      {
        "address": "0x43019f8be1f192587883b67dea2994999f5a2de2"
      }
    ],
    "optimism": [
      {
        "address": "0x1572d48a52906b834fb236aa77831d669f6d87a1"
      }
    ],
    "ethereum": [
      {
        "address": "0xb26b207de8478b85db7951e3ca3f39f2a6f5dad5"
      }
    ],
    "arbitrum": [
      {
        "address": "0x21f6ec768058ca2b3701099f7cea4c9a8cd63015"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.strike.org/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Strike",
  "domain": "app.strike.org",
  "chains": {
    "ethereum": [
      {
        "address": "0x3774e825d567125988fb293e926064b6faa71dab"
      },
      {
        "address": "0xe2e17b2cbbf48211fa7eb8a875360e5e39ba2602"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.takaralend.com/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Takaralend",
  "domain": "app.takaralend.com",
  "chains": {
    "avalanche": [
      {
        "address": "0x89c6340b1a1f4b25d36cd8b063d49045caf3f818"
      }
    ],
    "optimism": [
      {
        "address": "0x000000000022d473030f116ddee9f6b43ac78ba3"
      }
    ],
    "base": [
      {
        "address": "0x000000000022d473030f116ddee9f6b43ac78ba3"
      }
    ],
    "arbitrum": [
      {
        "address": "0x000000000022d473030f116ddee9f6b43ac78ba3"
      }
    ],
    "ethereum": [
      {
        "address": "0x000000000022d473030f116ddee9f6b43ac78ba3"
      }
    ],
    "celo": [
      {
        "address": "0x000000000022d473030f116ddee9f6b43ac78ba3"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.tinyworlds.io/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Tinyworlds",
  "domain": "app.tinyworlds.io",
  "chains": {
    "bsc": [
      {
        "address": "0x96eade4c5ca5251caa7801ed38fada4807f63cbe"
      },
      {
        "address": "0x390e1ba132ed9ff3394d8aa484983cc8c85f8149"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/scroll.io/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Scroll",
  "domain": "scroll.io",
  "chains": {
    "ethereum": [
      {
        "address": "0xf8b1378579659d8f7ee5f3c929c2f3e332e41fd6"
      },
      {
        "address": "0x6774bcbd5cecef1336b5300fb5186a12ddd8b367"
      }
    ],
    "scroll": [
      {
        "address": "0xe657243df50dbc60383f9504be22f7288174095c"
      },
      {
        "address": "0x7673f45e6e95373ba22651a4f5f594edec3006bc"
      },
      {
        "address": "0x7de3c253b3f28e78fa82273527b6da1f0b20c7df"
      },
      {
        "address": "0x65ab4b5f30aef8b29858ea2cbd6b0d0e68010206"
      },
      {
        "address": "0xb3faf6db995a063d020c3e4fcfbfdaa3f4e3e54e"
      },
      {
        "address": "0x5e9623b19b2ae231df659c6d88488fa21b17cc08"
      },
      {
        "address": "0xc2968d15a98406582a9fbc40c4508ce9cad4577e"
      },
      {
        "address": "0x13babb8c705506fd71f7e9aff431b9af2e659fe9"
      },
      {
        "address": "0xc47300428b6ad2c7d03bb76d05a176058b47e6b0"
      },
      {
        "address": "0x9c8a1c5b993baf52e9dd920181767b67bbd4d3a6"
      },
      {
        "address": "0x3aaa7472fb317fabc12aa0463b803d5f4f42c9f3"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/www.sushi.com/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Sushi",
  "domain": "www.sushi.com",
  "chains": {
    "gnosis": [
      {
        "address": "0x1e9b24073183d5c6b7ae5fb4b8f0b1dd83fdc77a"
      }
    ],
    "ethereum": [
      {
        "address": "0x827179dd56d07a7eea32e3873493835da2866976"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.baes.so/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Baes",
  "domain": "app.baes.so",
  "chains": {
    "base": [
      {
        "address": "0xb13655501ae155d2776e0069ee7b3ccf62308bcd"
      },
      {
        "address": "0x50b96f0808ff619affb8404ba83d7e712a21d57f"
      },
      {
        "address": "0x5876236942a5fb47cfa64d96e1792ae1426d09e5"
      },
      {
        "address": "0xb86932028bc6911303a7759aa34546675205717f"
      },
      {
        "address": "0xd7d7e5961d25c01fa1b7528869b228181d895000"
      },
      {
        "address": "0xdd896b710cc6a9bb69ea854db40e3565c373cbcb"
      },
      {
        "address": "0x07a56f0937192285e74abdd916c8ef7b311d1767"
      },
      {
        "address": "0xb16823c7aabc548b657087b76ef053a0f187269a"
      },
      {
        "address": "0x2b2e03ba6aa8d0f0129c8c7c192ce7a9bbb1f852"
      },
      {
        "address": "0x791978cf8d39866765f7a34ceb33114f2b862a17"
      },
      {
        "address": "0xd19dc8f69d0be79fa488f8ee72dcc46e1267da50"
      },
      {
        "address": "0x4bc14685708a803b36de324ad1ca1c7786400efc"
      }
    ]
  }
}
