=== LedgerHQ/web3allowlist/dapps/dapp-allowlist.schema.json
{
  "$id": "https://ledger.com/allowlist.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of a ledger allowlist",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "schemaVersion": {
      "type": "integer",
      "description": "The schema of the allowlist"
    },
    "$schema": {
      "type": "string",
      "description": "The schema of the allowlist"
    },
    "name": {
      "type": "string",
      "description": "The name of the allowlist"
    },
    "domain": {
      "type": "string",
      "description": "The domain of the allowlist"
    },
    "subdomains": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string",
      "description": "A description of the allowlist"
    },
    "chains": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/chain"
      }
    }
  },
  "required": ["name", "domain", "chains"],
  "$defs": {
    "chain": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/contract"
      }
    },
    "contract": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string",
          "description": "The address of the contract"
        },
        "description": {
          "type": "string",
          "description": "A description of the contract"
        }
      },
      "required": ["address"]
    }
  }
}

=== LedgerHQ/web3allowlist/dapps/studio.squidrouter/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Studio",
  "domain": "studio.squidrouter",
  "chains": {
    "arbitrum": [
      {
        "address": "0xce16f69375520ab01377ce7b88f5ba8c48f8d666"
      }
    ],
    "celo": [
      {
        "address": "0xce16f69375520ab01377ce7b88f5ba8c48f8d666"
      }
    ],
    "optimism": [
      {
        "address": "0xce16f69375520ab01377ce7b88f5ba8c48f8d666"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/native.org/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Native",
  "domain": "native.org",
  "chains": {
    "arbitrum": [
      {
        "address": "0xead050515e10fdb3540ccd6f8236c46790508a76"
      }
    ],
    "bsc": [
      {
        "address": "0xead050515e10fdb3540ccd6f8236c46790508a76"
      }
    ],
    "avalanche": [
      {
        "address": "0xead050515e10fdb3540ccd6f8236c46790508a76"
      }
    ],
    "ethereum": [
      {
        "address": "0xead050515e10fdb3540ccd6f8236c46790508a76"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/magiceden.io/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Magiceden",
  "domain": "magiceden.io",
  "chains": {
    "polygon": [
      {
        "address": "0xdef1c0ded9bec7f1a1670819833240f027b25eff"
      },
      {
        "address": "0x00000000000000adc04c56bf30ac9d3c0aaf14dc"
      }
    ],
    "ethereum": [
      {
        "address": "0x1231deb6f5749ef6ce6943a275a1d3e7486f4eae"
      },
      {
        "address": "0x0000000000000068f116a894984e2db1123eb395"
      }
    ],
    "base": [
      {
        "address": "0x0000000000000068f116a894984e2db1123eb395"
      }
    ],
    "arbitrum": [
      {
        "address": "0x0000000000000068f116a894984e2db1123eb395"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/salvor.io/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Salvor",
  "domain": "salvor.io",
  "chains": {
    "avalanche": [
      {
        "address": "0x0d15f99b6ae10cfa9a6d845b433ef51597c27e00"
      },
      {
        "address": "0xab4fe2d136efd7f8dfce3259a5e3c5e4c0130c80"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/bridge.telos.net/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Telos",
  "domain": "bridge.telos.net",
  "chains": {
    "bsc": [
      {
        "address": "0x9c5ebcbe531aa81bd82013abf97401f5c6111d76"
      }
    ],
    "arbitrum": [
      {
        "address": "0x9c5ebcbe531aa81bd82013abf97401f5c6111d76"
      }
    ],
    "ethereum": [
      {
        "address": "0x9c5ebcbe531aa81bd82013abf97401f5c6111d76"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/ens.domains/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Ethereum Naming Service",
  "domain": "*.ens.domains",
  "chains": {
    "ethereum": [
      {
        "address": "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
      },
      {
        "address": "0x314159265dD8dbb310642f98f50C066173C1259b"
      },
      {
        "address": "0x283Af0B28c62C092C9727F1Ee09c02CA627EB7F5"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/draculafi.xyz/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Draculafi",
  "domain": "draculafi.xyz",
  "chains": {
    "zksync": [
      {
        "address": "0x4d88434edc8b7ffe215ec598c2290cdc6f58d12d"
      },
      {
        "address": "0x1ba497d383cd7a500a8a25661598204247295a90"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.elk.finance/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Elk",
  "domain": "app.elk.finance",
  "chains": {
    "ethereum": [
      {
        "address": "0xb5e9f6c58f548cee53257304e287b23757effca1"
      },
      {
        "address": "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
      }
    ],
    "bsc": [
      {
        "address": "0xa63b831264183d755756ca9ae5190ff5183d65d6"
      },
      {
        "address": "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
      }
    ],
    "avalanche": [
      {
        "address": "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
      },
      {
        "address": "0x9e4aabd2b3e60ee1322e94307d0776f2c8e6cfbb"
      },
      {
        "address": "0x6352a56caadc4f1e25cd6c75970fa768a3304e64"
      }
    ],
    "fantom": [
      {
        "address": "0x4d2cf285a519261f30b4d9c2c344baf260d65fa2"
      },
      {
        "address": "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
      }
    ],
    "gnosis": [
      {
        "address": "0xe5759714998e8b50a33c7333c04c2d02e5dce77f"
      }
    ],
    "arbitrum": [
      {
        "address": "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
      },
      {
        "address": "0x0a2e5a3dc2f74e5bfaf0bf90685a5a899f379cb0"
      }
    ],
    "optimism": [
      {
        "address": "0xeade97afc8f79a8e5ba85d57c4a4e629b1160c6a"
      },
      {
        "address": "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
      }
    ],
    "base": [
      {
        "address": "0x7ae799fdbe4c330a4ac18d8d65765222a0d47e6d"
      }
    ]
  }
}
