=== LedgerHQ/web3allowlist/dapps/dapp-allowlist.schema.json
{
  "$id": "https://ledger.com/allowlist.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of a ledger allowlist",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "schemaVersion": {
      "type": "integer",
      "description": "The schema of the allowlist"
    },
    "$schema": {
      "type": "string",
      "description": "The schema of the allowlist"
    },
    "name": {
      "type": "string",
      "description": "The name of the allowlist"
    },
    "domain": {
      "type": "string",
      "description": "The domain of the allowlist"
    },
    "subdomains": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string",
      "description": "A description of the allowlist"
    },
    "chains": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/chain"
      }
    }
  },
  "required": ["name", "domain", "chains"],
  "$defs": {
    "chain": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/contract"
      }
    },
    "contract": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string",
          "description": "The address of the contract"
        },
        "description": {
          "type": "string",
          "description": "A description of the contract"
        }
      },
      "required": ["address"]
    }
  }
}

=== LedgerHQ/web3allowlist/dapps/tokentrove.com/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "TokenTrove",
  "domain": "tokentrove.com",
  "chains": {
    "ethereum": [
      {
        "address": "0x080bf510fcbf18b91105470639e9561022937712"
      },
      {
        "address": "0x4ef40d1bf0983899892946830abf99eca2dbc5ce"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.euler.finance/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Euler",
  "domain": "app.euler.finance",
  "chains": {
    "ethereum": [
      {
        "address": "0x1b808f49add4b8c6b5117d9681cf7312fcf0dc1d"
      },
      {
        "address": "0x0c9a3dd6b8f28529d72d7f9ce918d493519ee383"
      },
      {
        "address": "0x000000000022d473030f116ddee9f6b43ac78ba3"
      }
    ],
    "base": [
      {
        "address": "0x5301c7dd20bd945d2013b48ed0dee3a284ca8989"
      }
    ],
    "arbitrum": [
      {
        "address": "0x6302ef0f34100cddfb5489fbcb6ee1aa95cd1066"
      }
    ],
    "avalanche": [
      {
        "address": "0xddcbe30a761edd2e19bba930a977475265f36fa1"
      }
    ],
    "linea": [
      {
        "address": "0xd8cecee9a04ea3d941a959f68fb4486f23271d09"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/staging.hydrex.fi/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Hydrex",
  "domain": "staging.hydrex.fi",
  "chains": {
    "base": [
      {
        "address": "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
      },
      {
        "address": "0x0000000000001ff3684f28c67538d4d072c22734"
      },
      {
        "address": "0x6352a56caadc4f1e25cd6c75970fa768a3304e64"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.kiloex.io/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Kiloex",
  "domain": "app.kiloex.io",
  "chains": {
    "ethereum": [
      {
        "address": "0x1231deb6f5749ef6ce6943a275a1d3e7486f4eae"
      }
    ],
    "polygon": [
      {
        "address": "0x1231deb6f5749ef6ce6943a275a1d3e7486f4eae"
      }
    ],
    "bsc": [
      {
        "address": "0x1231deb6f5749ef6ce6943a275a1d3e7486f4eae"
      }
    ],
    "base": [
      {
        "address": "0x796f1793599d7b6aca6a87516546ddf8e5f3aa9d"
      },
      {
        "address": "0xdf5acc616cd3ea9556ec340a11b54859a393ebbb"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.holograph.xyz/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Holograph",
  "domain": "app.holograph.xyz",
  "chains": {
    "polygon": [
      {
        "address": "0x4f92ae4960a6ac49fa88bcf9d6d4b8c53f626a55"
      },
      {
        "address": "0x282d299ae68f40becc3c2a440e2894750b82de88"
      }
    ],
    "bsc": [
      {
        "address": "0x282d299ae68f40becc3c2a440e2894750b82de88"
      }
    ],
    "ethereum": [
      {
        "address": "0x282d299ae68f40becc3c2a440e2894750b82de88"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/app.lends.so/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Lends",
  "domain": "app.lends.so",
  "chains": {
    "avalanche": [
      {
        "address": "0x8f66c4ae756bebc49ec8b81966dd8bba9f127549"
      }
    ],
    "bsc": [
      {
        "address": "0xb30ec53f98ff5947ede720d32ac2da7e52a5f56b"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/pro.apex.exchange/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Apex",
  "domain": "pro.apex.exchange",
  "chains": {
    "polygon": [
      {
        "address": "0x10434755cfdcd34539db91c81ab0e07f96d44aa7"
      }
    ],
    "ethereum": [
      {
        "address": "0xe95b3dc78c0881dea17a69bafc6cfeb8d891e9de"
      },
      {
        "address": "0x379c15156b527d6e693bed60d1fbb44ce46046b8"
      }
    ],
    "bsc": [
      {
        "address": "0xe29304af265641a49f55294f7e5ba5010eba4497"
      },
      {
        "address": "0x7b71ff8451706b9e863879a84bf967ff4dc7a9bf"
      }
    ]
  }
}

=== LedgerHQ/web3allowlist/dapps/owlto.finance/dapp-allowlist.json
{
  "schemaVersion": 1,
  "$schema": "../dapp-allowlist.schema.json",
  "name": "Owlto",
  "domain": "owlto.finance",
  "chains": {
    "bsc": [
      {
        "address": "0x872fc5fed2d1261aba4e234a47f473c9a3da2724"
      }
    ],
    "base": [
      {
        "address": "0x26637c9fdbd5ecdd76a9e21db7ea533e1b0713b6"
      },
      {
        "address": "0xb5cedaf172425bdea4c186f6fcf30b367273da19"
      },
      {
        "address": "0x89d43d991f47924dd47c9b6a7fa17c6a15091999"
      },
      {
        "address": "0x44f32c85258d66327aeac9db6cb9446b7c0fb578"
      }
    ],
    "zksync": [
      {
        "address": "0xd48e3caf0d948203434646a3f3e80f8ee18007dc"
      },
      {
        "address": "0x95cdd9632c924d2cb5586168cf0ba7640df30598"
      },
      {
        "address": "0x1da58916f20f86d661f6b08985445a3ef36ffd92"
      }
    ],
    "scroll": [
      {
        "address": "0xa5a98e1e931a26213aa5a699d2f1bfbcf63999de"
      },
      {
        "address": "0xe6feca764b7548127672c189d303eb956c3ba372"
      },
      {
        "address": "0x575dbe0023d2602515a73d4f0b5ee857e8eba805"
      },
      {
        "address": "0x716d5dd0593ca5ddf8c91a9ee40685f7525e4fc6"
      }
    ],
    "avalanche": [
      {
        "address": "0x05c4c16f7aaf68efca9b32f5e6ae260fa2c26b2c"
      }
    ],
    "arbitrum": [
      {
        "address": "0x983811d9b6bed77b36818cb58fe49d91e2d8be98"
      },
      {
        "address": "0x0e83ded9f80e1c92549615d96842f5cb64a08762"
      }
    ],
    "optimism": [
      {
        "address": "0xd9d05c8971fb0e82f3640790fb845225a6e04af9"
      },
      {
        "address": "0x0e83ded9f80e1c92549615d96842f5cb64a08762"
      }
    ],
    "linea": [
      {
        "address": "0xd7487d1ff3b2433b32e6d4c333f70a462b99f300"
      }
    ]
  }
}
